"""phase3_story_intelligence

Revision ID: 8dec45ff778e
Revises: a6a68de3e40e
Create Date: 2026-07-05 04:59:24.383417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8dec45ff778e'
down_revision: Union[str, None] = 'a6a68de3e40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('si_story_versions',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_si_story_versions_entity', 'si_story_versions', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_si_story_versions_entity_id'), 'si_story_versions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_si_story_versions_entity_type'), 'si_story_versions', ['entity_type'], unique=False)
    op.create_table('si_generation_jobs',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=200), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_si_gen_jobs_project_status', 'si_generation_jobs', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_si_generation_jobs_job_type'), 'si_generation_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_si_generation_jobs_project_id'), 'si_generation_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_si_generation_jobs_status'), 'si_generation_jobs', ['status'], unique=False)
    op.create_table('si_worlds',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('locations', sa.JSON(), nullable=False),
    sa.Column('timeline_data', sa.JSON(), nullable=False),
    sa.Column('factions', sa.JSON(), nullable=False),
    sa.Column('objects', sa.JSON(), nullable=False),
    sa.Column('lore', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_si_worlds_project_id'), 'si_worlds', ['project_id'], unique=False)
    op.create_index(op.f('ix_si_worlds_status'), 'si_worlds', ['status'], unique=False)
    op.create_table('si_generation_logs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('retry_number', sa.Integer(), nullable=False),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['si_generation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_si_generation_logs_job_id'), 'si_generation_logs', ['job_id'], unique=False)
    op.create_table('si_retry_queue',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['si_generation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_si_retry_queue_job_id'), 'si_retry_queue', ['job_id'], unique=False)
    op.create_index(op.f('ix_si_retry_queue_status'), 'si_retry_queue', ['status'], unique=False)
    op.create_table('si_seasons',
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('story_arc', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('episode_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['si_worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'season_number', name='uq_season_world_number')
    )
    op.create_index(op.f('ix_si_seasons_project_id'), 'si_seasons', ['project_id'], unique=False)
    op.create_index(op.f('ix_si_seasons_status'), 'si_seasons', ['status'], unique=False)
    op.create_index(op.f('ix_si_seasons_world_id'), 'si_seasons', ['world_id'], unique=False)
    op.create_table('si_story_ideas',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('premise', sa.Text(), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=False),
    sa.Column('story_type', sa.String(length=100), nullable=False),
    sa.Column('target_audience', sa.String(length=200), nullable=False),
    sa.Column('estimated_episodes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('idea_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['si_worlds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_si_story_ideas_project_id'), 'si_story_ideas', ['project_id'], unique=False)
    op.create_index('ix_si_story_ideas_project_status', 'si_story_ideas', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_si_story_ideas_status'), 'si_story_ideas', ['status'], unique=False)
    op.create_index(op.f('ix_si_story_ideas_world_id'), 'si_story_ideas', ['world_id'], unique=False)
    op.create_table('si_story_memory',
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=500), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=True),
    sa.Column('embedding_vector', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['si_worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_si_story_memory_memory_type'), 'si_story_memory', ['memory_type'], unique=False)
    op.create_index(op.f('ix_si_story_memory_world_id'), 'si_story_memory', ['world_id'], unique=False)
    op.create_index('ix_si_story_memory_world_key', 'si_story_memory', ['world_id', 'key'], unique=False)
    op.create_index('ix_si_story_memory_world_type', 'si_story_memory', ['world_id', 'memory_type'], unique=False)
    op.create_table('si_episodes',
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('opening', sa.Text(), nullable=False),
    sa.Column('middle', sa.Text(), nullable=False),
    sa.Column('ending', sa.Text(), nullable=False),
    sa.Column('moral', sa.Text(), nullable=False),
    sa.Column('duration_target_seconds', sa.Integer(), nullable=False),
    sa.Column('story_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generation_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['si_seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['si_worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'episode_number', name='uq_episode_season_number')
    )
    op.create_index(op.f('ix_si_episodes_project_id'), 'si_episodes', ['project_id'], unique=False)
    op.create_index(op.f('ix_si_episodes_season_id'), 'si_episodes', ['season_id'], unique=False)
    op.create_index(op.f('ix_si_episodes_status'), 'si_episodes', ['status'], unique=False)
    op.create_index(op.f('ix_si_episodes_world_id'), 'si_episodes', ['world_id'], unique=False)
    op.create_table('si_story_evaluations',
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('evaluator_version', sa.String(length=20), nullable=False),
    sa.Column('originality_score', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('creativity_score', sa.Float(), nullable=False),
    sa.Column('grammar_score', sa.Float(), nullable=False),
    sa.Column('flow_score', sa.Float(), nullable=False),
    sa.Column('entertainment_score', sa.Float(), nullable=False),
    sa.Column('educational_value_score', sa.Float(), nullable=False),
    sa.Column('story_arc_score', sa.Float(), nullable=False),
    sa.Column('dialogue_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.JSON(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['si_episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_si_story_evaluations_episode_id'), 'si_story_evaluations', ['episode_id'], unique=False)
    op.create_table('si_story_scenes',
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('scene_goal', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('character_names', sa.JSON(), nullable=False),
    sa.Column('dialogue', sa.JSON(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('image_prompt', sa.Text(), nullable=False),
    sa.Column('animation_prompt', sa.Text(), nullable=False),
    sa.Column('camera_direction', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['si_episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_si_story_scenes_episode_id'), 'si_story_scenes', ['episode_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_si_story_scenes_episode_id'), table_name='si_story_scenes')
    op.drop_table('si_story_scenes')
    op.drop_index(op.f('ix_si_story_evaluations_episode_id'), table_name='si_story_evaluations')
    op.drop_table('si_story_evaluations')
    op.drop_index(op.f('ix_si_episodes_world_id'), table_name='si_episodes')
    op.drop_index(op.f('ix_si_episodes_status'), table_name='si_episodes')
    op.drop_index(op.f('ix_si_episodes_season_id'), table_name='si_episodes')
    op.drop_index(op.f('ix_si_episodes_project_id'), table_name='si_episodes')
    op.drop_table('si_episodes')
    op.drop_index('ix_si_story_memory_world_type', table_name='si_story_memory')
    op.drop_index('ix_si_story_memory_world_key', table_name='si_story_memory')
    op.drop_index(op.f('ix_si_story_memory_world_id'), table_name='si_story_memory')
    op.drop_index(op.f('ix_si_story_memory_memory_type'), table_name='si_story_memory')
    op.drop_table('si_story_memory')
    op.drop_index(op.f('ix_si_story_ideas_world_id'), table_name='si_story_ideas')
    op.drop_index(op.f('ix_si_story_ideas_status'), table_name='si_story_ideas')
    op.drop_index('ix_si_story_ideas_project_status', table_name='si_story_ideas')
    op.drop_index(op.f('ix_si_story_ideas_project_id'), table_name='si_story_ideas')
    op.drop_table('si_story_ideas')
    op.drop_index(op.f('ix_si_seasons_world_id'), table_name='si_seasons')
    op.drop_index(op.f('ix_si_seasons_status'), table_name='si_seasons')
    op.drop_index(op.f('ix_si_seasons_project_id'), table_name='si_seasons')
    op.drop_table('si_seasons')
    op.drop_index(op.f('ix_si_retry_queue_status'), table_name='si_retry_queue')
    op.drop_index(op.f('ix_si_retry_queue_job_id'), table_name='si_retry_queue')
    op.drop_table('si_retry_queue')
    op.drop_index(op.f('ix_si_generation_logs_job_id'), table_name='si_generation_logs')
    op.drop_table('si_generation_logs')
    op.drop_index(op.f('ix_si_worlds_status'), table_name='si_worlds')
    op.drop_index(op.f('ix_si_worlds_project_id'), table_name='si_worlds')
    op.drop_table('si_worlds')
    op.drop_index(op.f('ix_si_generation_jobs_status'), table_name='si_generation_jobs')
    op.drop_index(op.f('ix_si_generation_jobs_project_id'), table_name='si_generation_jobs')
    op.drop_index(op.f('ix_si_generation_jobs_job_type'), table_name='si_generation_jobs')
    op.drop_index('ix_si_gen_jobs_project_status', table_name='si_generation_jobs')
    op.drop_table('si_generation_jobs')
    op.drop_index(op.f('ix_si_story_versions_entity_type'), table_name='si_story_versions')
    op.drop_index(op.f('ix_si_story_versions_entity_id'), table_name='si_story_versions')
    op.drop_index('ix_si_story_versions_entity', table_name='si_story_versions')
    op.drop_table('si_story_versions')
    # ### end Alembic commands ###
