"""phase4_knowledge_engine

Revision ID: 9c163cebabb8
Revises: 8dec45ff778e
Create Date: 2026-07-06 09:12:20.637582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9c163cebabb8'
down_revision: Union[str, None] = '8dec45ff778e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kn_versions',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kn_versions_entity', 'kn_versions', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_kn_versions_entity_id'), 'kn_versions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_kn_versions_entity_type'), 'kn_versions', ['entity_type'], unique=False)
    op.create_table('kn_collections',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('collection_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('kn_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['si_worlds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kn_collections_project_id'), 'kn_collections', ['project_id'], unique=False)
    op.create_index('ix_kn_collections_project_status', 'kn_collections', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_kn_collections_status'), 'kn_collections', ['status'], unique=False)
    op.create_index(op.f('ix_kn_collections_world_id'), 'kn_collections', ['world_id'], unique=False)
    op.create_table('kn_documents',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('parsed_content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('kn_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['kn_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kn_documents_collection_id'), 'kn_documents', ['collection_id'], unique=False)
    op.create_index('ix_kn_documents_collection_status', 'kn_documents', ['collection_id', 'status'], unique=False)
    op.create_index(op.f('ix_kn_documents_content_hash'), 'kn_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_kn_documents_project_id'), 'kn_documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_kn_documents_status'), 'kn_documents', ['status'], unique=False)
    op.create_table('kn_retrieval_history',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_source', sa.String(length=100), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('top_score', sa.Float(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['kn_collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kn_retrieval_history_collection_id'), 'kn_retrieval_history', ['collection_id'], unique=False)
    op.create_index('ix_kn_retrieval_history_project', 'kn_retrieval_history', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_kn_retrieval_history_project_id'), 'kn_retrieval_history', ['project_id'], unique=False)
    op.create_table('kn_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('embedding_model', sa.String(length=200), nullable=False),
    sa.Column('embedding_dims', sa.Integer(), nullable=False),
    sa.Column('is_embedded', sa.Boolean(), nullable=False),
    sa.Column('kn_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['kn_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['kn_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_kn_chunk_document_index')
    )
    op.create_index('ix_kn_chunks_collection_embedded', 'kn_chunks', ['collection_id', 'is_embedded'], unique=False)
    op.create_index(op.f('ix_kn_chunks_collection_id'), 'kn_chunks', ['collection_id'], unique=False)
    op.create_index(op.f('ix_kn_chunks_document_id'), 'kn_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_kn_chunks_is_embedded'), 'kn_chunks', ['is_embedded'], unique=False)
    op.create_table('kn_embedding_jobs',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=200), nullable=False),
    sa.Column('chunks_processed', sa.Integer(), nullable=False),
    sa.Column('chunks_total', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['kn_collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['kn_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kn_embedding_jobs_collection_id'), 'kn_embedding_jobs', ['collection_id'], unique=False)
    op.create_index(op.f('ix_kn_embedding_jobs_document_id'), 'kn_embedding_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_kn_embedding_jobs_job_type'), 'kn_embedding_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_kn_embedding_jobs_project_id'), 'kn_embedding_jobs', ['project_id'], unique=False)
    op.create_index('ix_kn_embedding_jobs_project_status', 'kn_embedding_jobs', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_kn_embedding_jobs_status'), 'kn_embedding_jobs', ['status'], unique=False)
    op.create_table('kn_memory',
    sa.Column('world_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('memory_type', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=500), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['kn_collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['kn_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['world_id'], ['si_worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kn_memory_collection_id'), 'kn_memory', ['collection_id'], unique=False)
    op.create_index(op.f('ix_kn_memory_memory_type'), 'kn_memory', ['memory_type'], unique=False)
    op.create_index(op.f('ix_kn_memory_project_id'), 'kn_memory', ['project_id'], unique=False)
    op.create_index('ix_kn_memory_project_type', 'kn_memory', ['project_id', 'memory_type'], unique=False)
    op.create_index(op.f('ix_kn_memory_world_id'), 'kn_memory', ['world_id'], unique=False)
    op.create_index('ix_kn_memory_world_type', 'kn_memory', ['world_id', 'memory_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kn_memory_world_type', table_name='kn_memory')
    op.drop_index(op.f('ix_kn_memory_world_id'), table_name='kn_memory')
    op.drop_index('ix_kn_memory_project_type', table_name='kn_memory')
    op.drop_index(op.f('ix_kn_memory_project_id'), table_name='kn_memory')
    op.drop_index(op.f('ix_kn_memory_memory_type'), table_name='kn_memory')
    op.drop_index(op.f('ix_kn_memory_collection_id'), table_name='kn_memory')
    op.drop_table('kn_memory')
    op.drop_index(op.f('ix_kn_embedding_jobs_status'), table_name='kn_embedding_jobs')
    op.drop_index('ix_kn_embedding_jobs_project_status', table_name='kn_embedding_jobs')
    op.drop_index(op.f('ix_kn_embedding_jobs_project_id'), table_name='kn_embedding_jobs')
    op.drop_index(op.f('ix_kn_embedding_jobs_job_type'), table_name='kn_embedding_jobs')
    op.drop_index(op.f('ix_kn_embedding_jobs_document_id'), table_name='kn_embedding_jobs')
    op.drop_index(op.f('ix_kn_embedding_jobs_collection_id'), table_name='kn_embedding_jobs')
    op.drop_table('kn_embedding_jobs')
    op.drop_index(op.f('ix_kn_chunks_is_embedded'), table_name='kn_chunks')
    op.drop_index(op.f('ix_kn_chunks_document_id'), table_name='kn_chunks')
    op.drop_index(op.f('ix_kn_chunks_collection_id'), table_name='kn_chunks')
    op.drop_index('ix_kn_chunks_collection_embedded', table_name='kn_chunks')
    op.drop_table('kn_chunks')
    op.drop_index(op.f('ix_kn_retrieval_history_project_id'), table_name='kn_retrieval_history')
    op.drop_index('ix_kn_retrieval_history_project', table_name='kn_retrieval_history')
    op.drop_index(op.f('ix_kn_retrieval_history_collection_id'), table_name='kn_retrieval_history')
    op.drop_table('kn_retrieval_history')
    op.drop_index(op.f('ix_kn_documents_status'), table_name='kn_documents')
    op.drop_index(op.f('ix_kn_documents_project_id'), table_name='kn_documents')
    op.drop_index(op.f('ix_kn_documents_content_hash'), table_name='kn_documents')
    op.drop_index('ix_kn_documents_collection_status', table_name='kn_documents')
    op.drop_index(op.f('ix_kn_documents_collection_id'), table_name='kn_documents')
    op.drop_table('kn_documents')
    op.drop_index(op.f('ix_kn_collections_world_id'), table_name='kn_collections')
    op.drop_index(op.f('ix_kn_collections_status'), table_name='kn_collections')
    op.drop_index('ix_kn_collections_project_status', table_name='kn_collections')
    op.drop_index(op.f('ix_kn_collections_project_id'), table_name='kn_collections')
    op.drop_table('kn_collections')
    op.drop_index(op.f('ix_kn_versions_entity_type'), table_name='kn_versions')
    op.drop_index(op.f('ix_kn_versions_entity_id'), table_name='kn_versions')
    op.drop_index('ix_kn_versions_entity', table_name='kn_versions')
    op.drop_table('kn_versions')
    # ### end Alembic commands ###
